apiVersion: v1
kind: Pod
metadata:
  name: mq-pod
  labels:
    app: RabbitMQ
spec:
  containers:
  - name: my-rabbit
    image: rabbitmq:3.7.7-management
    ports:
    - name: mq-port
      containerPort: 5672
    - name: management-port
      containerPort: 15672
